community/urls.py
from django.urls import path
# from community.views import write, list
from community import views
 
# app_name="community"    
urlpatterns = [
    # write/ 요청이 들어오면, views.write()함수 실행
    # path('write/', views.write, name="wirte"),
    path('write/', views.WriteFormView.as_view(), name="write"),
    # community/list/
    # path('lists/', views.list, name="list"),
    path('lists/', views.ArticleListView.as_view(), name="list"),
    # view_detail/4
    # path('view_detail/<int:num>/', views.viewDetail, name="view_detail"),
    path('view_detail/<int:pk>/', views.ArticleViewDetail.as_view(), name="view_detail"),
    # /change/
    path('change/', views.ArticleChangeView.as_view(), name="change"),

    # 1/update/
    path('<int:pk>/update/', views.ArticleUpdateView.as_view(), name="update"),

    # 1/delete/
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name="delete"),
]

django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
# from community.views import write, list
from community import views 

# from .views import UserCreateView, UserCreateDoneTV
from . import views as av

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # 홈 path '/' : 오류남
    # path('', av.home, name="home"),
    # CBV 방식 path
    path('', av.Home.as_view(), name="home"),

    # community 앱의 path를 포함시킴
    path('community/', include('community.urls')),
    path('dashboard/', include('dashboard.urls')),

    # django.contrib.auth.urls 장고 내장 인증 urls 활용
    path('accounts/', include('django.contrib.auth.urls')),

    # 회원가입 처리 path
    # UserCreateView.as_view() : 클래스형 view 호출방법
    path('accounts/register/', av.UserCreateView.as_view(), name="register"),
    # 계정생성이 완료됐다는 메시지를 보여는 path
    path('accounts/register/done/', av.UserCreateDoneTV.as_view(), name='register_done'),
   ]

community/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Article(models.Model):
  name = models.CharField(max_length=20)
  title = models.CharField(max_length=50)
  contents = models.TextField()
  url = models.URLField()
  email = models.EmailField()
  cdate = models.DateTimeField(auto_now_add=True)
  mdate = models.DateTimeField(auto_now=True)
  # on_delete=models.CASCADE : 계정이 삭제 되면 그 계정이 삭제한 글도 삭제함
  # blank=True : 입력폼에서 비어있는 것 허용
  # null=True : 테이블의 owner 컬럼에 빈값을 허용
  owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

  class Meta:
    verbose_name_plural = "아티클 작성하기"
    ordering=('-mdate',)  # mdate 기준 내림차순 정렬

  # 문자열 format : title, name, cdate
  def __str__(self):
    return f"{self.title} : {self.name} : {self.cdate}"
  
  def get_absolute_url(self):
    # view_detail : path 이름
    return reverse('view_detail', args=(self.id,))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css">
    
  <!-- <link rel="stylesheet" href="static/sytle.css"> -->

  <!-- css 적용 부분 -->
  {% block sytle %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"></script>
  <title>{% block title %}코즈랩홈{% endblock %}</title>
</head>
<body>
  <!-- naver 영역 -->
  {% include "navbar.html" %}

  <div class="container contents">
    <!-- 각페이지의 콘텐츠  영역 -->
    {% block container %}
    {% endblock %}

  </div>

  <!-- footer 영역 -->
  {% include "footer.html" %}
</body>
</html>
<!-- 
  html 태그로 js파일 연결
  static load
 -->
 <script src="{% static 'js/main.js' %}"></script>

templates/footer.html
<footer class="text-bg-secondary p-3 fixed-bottom">
  <div class="container">
    <address>경기도 성남시 분당구 야탑동</address>
    <p>대표이사 : 김경하</p>
  </div>
</footer>

templates/index.html
{% extends "base.html" %}
<!-- head tag의 타이틀 -->
{% block title %}코즈랩홈{% endblock %}


{% block container %}

<!-- 페이지 콘텐츠 영역 -->
<h1>메모 최근 목록</h1>
<ul>
  {% for article in article_list %}
    <li>
      <a href="/community/view_detail/{{ article.id }}/">
        {{ article.title }}
      </a> | 
      {{ article.name }} | 
      {{ article.cdate }}
    </li>
  {% endfor %}
</ul>
<a href="/community/write/"><input type="button" value="메모작성하기"></a>
<!-- <button>메모작성하기</button> -->
{% endblock %}

templates/list.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <p>이름 | 제목 | 작성 날짜</p>
  <ul>
  <!-- {{ article_list }} -->
  {% for article in  article_list %}
    <li>
      <a href="/view_detail/{{ article.id }}/">
        {{ article.title }} 
      </a>| 
      {{ article.name }} | 
      {{ article.email }} | 
      {{ article.cdate|date:"Y년 M d일 D" }}
    </li>
  {% endfor %}
  </ul>
  
  
  

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark text-bg-primary">
  <div class="container-fluid container">
    <a class="navbar-brand" href="{% url 'home' %}">Cozlab</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <!-- <a class="nav-link active" aria-current="page" href="/community/list/">커뮤니티</a> -->
          <!-- template 태그 블럭 주석 -->
          {% comment "community:list => appname:path_name" %}
          <a class="nav-link active" aria-current="page" href="{% url 'community:list' %}">커뮤니티</a>
          {% endcomment %}
          <a class="nav-link active" aria-current="page" href="{% url 'list' %}">커뮤니티</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard' %}">인구대시보드</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">포트폴리오</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">토이프로젝트</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            유틸스
          </a>
          <ul class="dropdown-menu ">
            <li>
              <a class="dropdown-item" href="{% url 'write' %}">글작성</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'change' %}">나의글목록</a>
            </li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- 로그인 / 회원가입 인증 부분 -->
    <div class="navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <!-- 로그인 했을 때 -->
          {% if user.is_active %}
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <!-- userid -->
              {{ user.username }}
            </a>
            <ul class="dropdown-menu ">
              <li><a class="dropdown-item" href="{% url 'password_change' %}">비밀번호변경</a></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a></li>
            </ul>

          <!-- 로그인 하지 않았을 때 -->
          {% else %}
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Anonymous
            </a>
            <ul class="dropdown-menu ">
              <li><a class="dropdown-item" href="{% url 'login' %}">로그인</a></li>
              <li><a class="dropdown-item" href="{% url 'register' %}">회원가입</a></li>
            </ul>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>